export const SECTIONS = [
  { label: "Shop", value: "shop", endpoint: "/shop/get-entries" },
  { label: "Dealer", value: "dealer", endpoint: "/dealer/entries" },
  { label: "Profit / Commission", value: "profit", endpoint: "/profit/entries" },
  { label: "Delivery Cost", value: "delivery-cost", endpoint: "/delivery-cost/entries" },
];

export const COLUMNS: Record<string, { label: string; key: string }[]> = {
  shop: [
    { label: "Date", key: "date" },
    { label: "Month", key: "month" },
    { label: "Product Details", key: "productDetails" },
    { label: "Quantity", key: "quantity" },
    { label: "Product Value", key: "productValue" },
    { label: "Total Cost", key: "totalCost" },
    { label: "Previous Due", key: "previousDue" },
    { label: "Deposit", key: "deposit" },
    { label: "Truck Fair", key: "truckFair" },
    { label: "Rest Total Amount", key: "restTotalAmount" },
    { label: "Sign", key: "sign" },
  ],
  dealer: [
    { label: "Date", key: "date" },
    { label: "Month", key: "month" },
    { label: "DO Dhaka", key: "doDhaka" },
    { label: "DO Ghat", key: "doGhat" },
    { label: "Bank Deposit", key: "bankDeposit" },
    { label: "Adv DO Qty", key: "advDoQty" },
    { label: "DO Lifting", key: "doLifting" },
    { label: "Excess DO Qty", key: "excessDoQty" },
    { label: "Delivered Party", key: "deliveredPartyName" },
    { label: "Delivered Qty", key: "deliveredQty" },
  ],
  profit: [
    { label: "Date", key: "date" },
    { label: "Month", key: "month" },
    { label: "Retail/Site", key: "retailSite" },
    { label: "Qty", key: "qty" },
    { label: "DO Rate", key: "doRate" },
    { label: "Truck Fair", key: "truckFair" },
    { label: "Total", key: "total" },
    { label: "Landing Rate", key: "landingRate" },
    { label: "COM", key: "com" },
    { label: "After COM Rate", key: "afterComRate" },
    { label: "Profit/Loss", key: "profitLoss" },
    { label: "Net Profit", key: "netProfit" },
    { label: "Remarks", key: "remarks" },
  ],
  "delivery-cost": [
    { label: "Date", key: "date" },
    { label: "Month", key: "month" },
    { label: "Serial No", key: "serialNumber" },
    { label: "Retail/Site", key: "retailSite" },
    { label: "Bag", key: "bag" },
    { label: "Car Cost", key: "carCost" },
    { label: "DO Give", key: "doGive" },
    { label: "DO Take", key: "doTake" },
    { label: "Gift", key: "gift" },
  ],
};